export const ROUTES = {
	HOME: '/',
	PROFILE: '/profile',
	EXECUTOR: '/profile/executor',
	DASHBOARD: '/profile/dashboard',
	MY_RECORDS: '/profile/records',
	MY_REVIEWS: '/profile/reviews',
	MY_ORDERS: '/profile/orders',
	FAVORITES: '/profile/favorites',
	SETTINGS: '/settings',
	STAFF: '/profile/staff',
	SERVICES: '/profile/services',
	PREMIUM_SERVICES: '/profile/premium-services',
	STAFF_PROFILE: (id: number) => `/profile/staff/${id}`,
	//ADMIN
	ADMIN: {
		CATEGORIES: '/admin/categories',
		SERVICE_TYPES: '/admin/service-types',
		SERVICES: '/admin/services',
		ORDERS: '/admin/orders',
		REVIEWS: '/admin/reviews',
		USERS: '/admin/users',
		SETTINGS: '/admin/settings',
		STAFF: '/admin/staff',
		STAFF_PROFILE: (id: number) => `/admin/staff/${id}`,
	},
} as const
